// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fixbjwnzqeuhzkuupdpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpeGJqd256cWV1aHprdXVwZHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjA4ODksImV4cCI6MjA2Mjc5Njg4OX0.N1A16pVrWMOntoU0vsE4ThcF1AhsllTrqbKQpiXwvNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);